src/app/home.component.html

Incorporating feedback from @Blackbaud-PaulCrowder to use `info` instead of `warning`.

Using info instead of warning

---

src/app/learn/get-started/prereqs/ssl-certificate/index.html

I tested these instructions on `FF 58.0b14` on macos.

Instructions for installing the certificate for Firefox

---

src/app/components/tile/index.html

Based on https://github.com/blackbaud/skyux2/blob/master/src/modules/tiles/tile/tile.component.ts and https://github.com/blackbaud/skyux2/blob/master/src/modules/tiles/tile/fixtures/tile.component.fixture.html, I assumed we just need to change `isCollapsedChanged` to `isCollapsedChange`. While making this change I also noticed a misspelling ("bulding" instead of "building") and decided to make a few quick style/grammar fixes as well.

Fix tile event name, plus other doc tweaks.

---

src/app/learn/get-started/prereqs/initial-setup/index.html
src/app/learn/get-started/prereqs/ssl-certificate/index.html

Received feedback from a user completing SKY UX prereqs for a new Stache site. This PR provides suggested edits based on the user's issues. 
- Didn't know how to download the SSL cert. (if you click the link, it just opens)
- Didn't realize when we say don't use node 7+ that means don't use numbers higher than 7 (ex. 8)
- The link to node was confusing too, since we take them to the latest release page.
I also re-worded the Git section to better match node.js section, and make it clearer you need to install Git.

edit docs based on user feedback

---

src/app/components/list/grid/index.html

The link for "the sky-grid component" was actually pointing to the documentation for the List overview and not for the sky-grid page.

Update link to sky-grid on the sky-list page

---

.gitignore
package.json
src/app/components/shared/demo-page-code.component.scss
src/app/components/shared/demo-page-plunker-service.ts
src/app/learn/get-started/advanced/route-params/index.html
src/app/styles.scss

This makes test https://github.com/blackbaud/skyux2/pull/1491 easier to test.  I should mention, I wasn't able to solve the `takeUntil` error on the `list-view-grid`.  Line 194 is an attempt to quickly solve that in the docs (for now).
To test:
- `npm install -g serve` (or similar package).  The latest version of `serve` inadvertently made node >= 7.6 a requirement.  For now, I would run `npm install -g serve@6.5.3`.  https://github.com/zeit/serve/issues/348
- In skyux repo
- `npm run build`
- `serve . --cors --ssl --cache 0` (or similar command)
- Open `https://localhost:5000` and approve SSL cert
- In skyux2-docs repo
- `skyux serve`
I did evaluate StackBlitz, and think that will be a logical move for us, but am waiting on https://github.com/stackblitz/core/issues/437 before investing …

Updated plunker service to specify versions of NG + RXJS.

---

src/app/learn/get-started/prereqs/initial-setup/index.html

Suggesting an edit for Windows users to specify which Node.js option to download from the v6 list.

added tip for which v6 option to download

---

src/app/components/wait/index.html

John, feel free to English me on that line, and Steve, keep me honest, please. :)

added ariaLabel to properties

---

package.json
src/app/components/modal/index.html

Added beforeClose event to modal docs

---

src/app/learn/reference/configuration/index.html

Moving the new content within the `li` tag for the example that it is describing so that the indent coincides with what's being described.

Adjust indent on new config docs

---

src/app/design/guidelines/buttons-links/index.html
src/app/design/guidelines/call-out-info/index.html
src/app/design/guidelines/content-containers/index.html
src/app/design/guidelines/error-handling/index.html
src/app/design/guidelines/filtering-lists/index.html
src/app/design/guidelines/form-design/index.html
src/app/design/guidelines/managing-records/index.html
src/app/design/guidelines/page-layouts/index.html
src/app/design/styles/borders/index.html
src/app/design/styles/color/index.html
src/app/design/styles/icons/index.html
src/app/design/styles/motion/index.html
src/app/design/styles/spacing/index.html
src/app/design/styles/typography/index.html
src/app/learn/reference/configuration/index.html

Addresses https://github.com/blackbaud/skyux2/issues/2308.

Update page title guidance and docs cleanup

---

src/app/learn/reference/configuration/index.html

added the missing s in excludeFromRequests. It's correct in the description but incorrect in the bulleted list

added missing s

---

src/app/learn/reference/configuration/index.html

Addresses https://github.com/blackbaud/skyux2-docs/issues/334, https://github.com/blackbaud/skyux2-docs/issues/254, and https://github.com/blackbaud/skyux2-docs/issues/253. Also cleans up and/or expands documentation for a few other configuration options.

Update configuration documentation

---

src/app/components/modal/index.html

Based on the Slack thread, I took away that we just needed to call out the values. Let me know if we need to make a proper section for this.
Addresses https://github.com/blackbaud/skyux2-docs/issues/258

Added values for reason property in skyCloseModalArgs

---

src/app/contribute/packages/packages.component.ts

`@skyux/validation` package was listed twice.

Remove duplicate item

---

src/app/components/datepicker/index.html

Issue: https://github.com/blackbaud/skyux2-docs/issues/399
As of `@skyux/datetime@3.2.0`, setting `skyDatepickerInput` to a reference of `<sky-datepicker>` is not required (the consumer can simply provide `skyDatepickerInput`):
**Before:**
```
<sky-datepicker #mypicker>
<input [skyDatepickerInput]="mypicker" />
</sky-datepicker>
```
**After:**
```
<sky-datepicker>
<input skyDatepickerInput />
</sky-datepicker>
```
The demo is being updated, here: https://github.com/blackbaud/skyux2/pull/2347

Update datepicker API

---

src/app/learn/reference/helpers/index.html

Updated the `SkyAuthClientHttpModule` to `SkyAuthHttpClientModule` to reflect the actual module name.

Fix "SkyAuthClientHttpModule" typo in reference section

---

src/app/components/list/paging/index.html

Module actually lives in `skyux-list-builder` not `skyux-lists`.
https://github.com/blackbaud/skyux-list-builder/blob/master/src/app/public/modules/list-paging/list-paging.module.ts

updated module export location

---

src/app/components/grid/index.html
src/app/components/list/grid/index.html
src/app/components/tile/index.html
src/app/design/guidelines/user-assistance/index.html
src/app/learn/get-started/basics/create-project/index.html
src/app/learn/reference/configuration/index.html

This PR includes some of the updates we discussed on the phone, plus a couple style things (one where I rearranged text because a code snippet was smashed up against regular text even though there was a space in the code and one where I changed a p tag back to an alert after reconsidering a recent change). We still need to resolve some of the other issues about how to make the restricted view stuff work, but talking to Tim late Friday afternoon, I think it's doable to update the restricted view library so that there is an option to display one thing for logged in users and a totally different thing for non-logged in users. If so, that would go a long way to addressing the issues we are running into. ... Anyway, hopefully that gives you enough to go on when discussing this with Todd and …

Tweak restricted view updates

---

.travis.yml

The build has started failing, as seen with https://github.com/blackbaud/skyux2-docs/pull/641.
The code comment in `.travis.yml` suggests looking at http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/, but that link no longer works.
https://docs.travis-ci.com/user/chrome seems to suggest a simpler approach, likely not available when this repo was first created.  This PR is using the documented approach.

Updated .travis.yml to use new Chrome addon technique.

---

src/app/components/demo-components.service.ts

Addresses https://github.com/blackbaud/skyux2-docs/issues/643, and also updates missing dependencies for buttons that work but load the demos without the necessary dependencies.

Hide StackBlitz buttons that do not work and add missing dependencies

---

src/app/components/dropdown/index.html

We've talked about changing the name of this component to avoid usage confusion, but I don't think this is what we had in mind...

Fix typo in Dropdown page title

---

package-lock.json
src/app/shared/home-component/home.component.html
src/app/shared/home-component/home.component.scss

We could update the image from https://carbon.now.sh/ApwqHQj44GE1WHw6tdoU, but I liked @michael-tims suggestion of using code.  We tried this in the past and it visually just wasn't as appealing.  I'm OK with the visual look now.
Fixes https://github.com/blackbaud/skyux2-docs/issues/718

Used text instead of an image to call out the correct SDK + getting started guide

---

skyuxconfig.json
src/app/design/ux-action-button.component.ts

There is a bug with the way Sketch and Axure interact with Blackbaud Sans. Removing the design resources page until the libraries are fixed.

remove design resources temporarily

---

src/app/components/icon/index.html
src/app/design/styles/icons/index.html

Addresses https://github.com/blackbaud/skyux2-docs/issues/727. ... This addresses the point that an external developer raised about the `fa fa-` classes. But it does not include anything about how to color the icon using one of the appropriate styles as @Blackbaud-BenLambert suggested. Do we want to include anything about that? And if so, what guidance do we want to provide?

Update icon docs

---

src/app/components/page-summary/index.html

I looked at adding this info at the end in a UX guidelines section and higher up in a section like the others on the page and opted for the former. We can move as necessary. ... I'll circle back to get rid of multiple instances of empty table headers, but I wanted to go ahead and get the the toolbar updates in place first.

Add toolbar info to page summary docs

---

src/app/components/page-summary/index.html

Update the new page summary guidelines to include guidance from https://developer.blackbaud.com/skyux/components/toolbar#ux-guidelines as per recommendation from @Blackbaud-ToddRoberts.

Expand toolbar guidelines

---

src/app/components/confirm/index.html

Addresses the guideline portion of https://github.com/blackbaud/skyux-modals/issues/124. (@Blackbaud-AdamFunderburk, this is based on your feedback to a question about confusing confirmation buttons on a Slack thread awhile back, which is why I added you as a reviewer.)

Update button label guidance for confirm component

---

src/app/components/shared/demo-page.component.html

Addresses https://github.com/blackbaud/skyux2-docs/issues/729.
@Blackbaud-AdamFunderburk and/or @Blackbaud-ToddRoberts, the docs issue indicates that leaving breadcrumbs off of phase 2 docs was a deliberate change to see if it bothered anyone. Given that we never heard any complaints, I'm removing the breadcrumbs for consistency. As we migrate content to the component repos, the breadcrumbs would eventually be removed anyway, but this knocks it all out at once for consistency. ... Also, I confirmed with Steve that to enable breadcrumbs in docs-tools is going to be a dev change, so if we change our minds, it will require a dev issue in the docs-tools reapo.

Remove breadcrumbs for Component section for consistency

---

package-lock.json
package.json

This was done (and the builder release created) in order to get e2e / Stache Search builds to pass.  It is necessary so we can continue to contribute content until we're able to upgrade to SKY UX 4.

Upgrading to latest 3.x version of @skyux-sdk/builder

---

src/stache/includes/supported-browsers.html

We were asked to update docs on browser support to point to IT's new central resource for supported browser guidance, so I updated our content to just link to the new guidance given that it seemed to be completely in sync (only with more details in the new guidance).

Update browser support info
