- src/app/components/filter/index.html
- src/app/components/list-view-grid/index.html
- src/app/components/sort/index.html
Documentation for blackbaud/skyux2#1364
> Updated documentation to go with Skyux 2 PR 1364

- src/app/learn/reference/configuration/apply-appsettings/index.html
Addresses https://github.com/blackbaud/skyux2/issues/863
> Marking config as public so it's accessible in template

- src/app/components/filter/index.html
- src/app/components/list-view-grid/index.html
- src/app/components/sort/index.html
@Blackbaud-TrevorBurch is the original owner via #13
> Updated documentation to go with Skyux 2 PR 1364 (#13)

- src/app/components/demo-components.service.ts
- src/app/components/flyout/index.html
@Blackbaud-SteveBrush: I had a lot of little tweaks, enough so that I decided to create a new PR to merge them into your `flyout` branch rather than make the edits directly in the `flyout` branch. If you could give the changes a quick edit to make sure I didn't get anything wrong, I'd really appreciate it. Thanks.
> Flyout docs edits

- package.json
- src/app/components/demo-components.service.ts
- src/app/components/flyout/index.html
@blackbaud-johnly Feel free to adjust as needed!
> Added docs for flyout component

- src/app/learn/get-started/basics/run-tests/index.html
Previously `skyux watch` was mentioned, but not directly explained.
> Describe skyux watch in Basics > Run Tests

- src/app/learn/get-started/advanced/localization/index.html
Quick fix from glancing over the localization docs
> Close stache-code block

- src/app/learn/get-started/advanced/route-params/index.html
Updated the route parameters docs based on feedback this morning.
> Call out that builder converts variable to string.

- skyuxconfig.json
- src/app/blog/index.html
Needs the Autocomplete docs merged in first, if possible.
> blog and first post

- src/app/design/guidelines/error-handling/index.html
- src/app/design/guidelines/form-design/index.html
- src/app/design/guidelines/guideline-action-button.component.ts
@Blackbaud-ToddRoberts, I created a separate PR so that you could see the tweaks I was suggesting to your updates. Unfortunately, because I also adjusted spacing as I went, the tweaks don't stand out as much as I'd hoped. Sorry about that. (Also, I'm not sure why the spacing changes look like so spaced out in the GitHub UI. In VSCode, I added tab indents with 2 spaces, which is the SKY UX style. It looks right in my editor, but in GitHub, there is all sorts of extra space.)
> Doc edits for design guideline updates.

- src/app/learn/reference/configuration/additional-config-files/index.html
- src/app/learn/reference/configuration/index.html
@Blackbaud-SteveBrush, this addresses https://github.com/blackbaud/skyux2/issues/1484, which we discussed. And @blackbaud-brandonhare, this adds the envid/svcid content for local development that we discussed.
> Address feedback on config file and params property.

- src/app/components/flyout/flyout-guidelines.component.html
- src/app/design/guidelines/content-containers/index.html
@Blackbaud-ToddRoberts, I didn't mess with spacing this time, so it should be easier to see what I edited. Thanks.
> Flyout ux guidelines edits

- src/app/design/styles/color/index.html
Addresses https://github.com/blackbaud/skyux2/issues/1581.
> Document how to import color SCSS variables.

- src/app/components/demo-components.service.ts
Addresses https://github.com/blackbaud/skyux2/issues/1591
> Fix component alphabetical order

- src/app/learn/get-started/basics/navigate-spa/index.html
This updates the SkyAppLink docs to reflect the changes in https://github.com/blackbaud/skyux-builder/pull/402. Need to wait on that release to update the docs.
> Add reference to excluding defaults.

- .gitignore
- package.json
- src/app/components/shared/demo-page-code.component.scss
- src/app/components/shared/demo-page-plunker-service.ts
- src/app/learn/get-started/advanced/route-params/index.html
- src/app/styles.scss
~~~Works with the recent edits to: https://github.com/blackbaud/skyux2/pull/1491~~~ (released in 2.12.2)
Also addresses: https://github.com/blackbaud/skyux2/issues/1308
> Added rxjs bundle

- src/app/components/flyout/index.html
Addresses: https://github.com/blackbaud/skyux2/issues/1703
> Flyout > Permalink and width docs

- package.json
- src/app/components/demo-components.service.ts
- src/app/components/infinite-scroll/index.html
Original contribution: https://github.com/blackbaud/skyux2-docs/pull/64
> added documentation for the infinite-scroll component (#64)

- src/app/components/shared/demo-page-plunker-service.ts
Simply added `RouterModule.forRoot`
> Fixed plunker for modal

- src/app/learn/reference/component-libraries/index.html
Addresses: https://github.com/blackbaud/skyux2/issues/1697
> Updated library configuration docs

- src/app/learn/get-started/basics/serve-project/index.html
PR with feedback from @blackbaud-johnly
> Adding missing enableProdMode HOWTOUpdate index.html

- src/app/components/shared/demo-page-plunker-service.ts
Reference this pull request in order to test the changes:
https://github.com/blackbaud/skyux2-docs/pull/82
> Fixed microedge imports for plunker

- src/app/design/guidelines/page-layouts/index.html
Addresses https://github.com/blackbaud/skyux-design/issues/146.
> Add missing link to page design guidelines

- src/app/components/grid/index.html
- src/app/components/list/grid/index.html
Resolves https://github.com/blackbaud/skyux2/issues/1906. ... The update is merged in https://github.com/blackbaud/skyux2/pull/1897, but marking as hold until the next SKY UX release.
> Document selectedColumnIdsChange property for list view grids

- src/app/components/shared/demo-page-plunker-service.ts
Resolves blackbaud/skyux2#1769
> Add rjxs operators to overall Plunker imports

- src/app/components/list/toolbar/index.html
Addresses https://github.com/blackbaud/skyux2/issues/1810. In addition to adding an entry for `sky-list-toolbar-view-actions`, I also cleaned up a variety of things in the existing docs. And I have a list of questions to follow up on for the list toolbar docs.
> Document view actions component

- package.json
Resolves: https://github.com/blackbaud/skyux2/issues/1980
> Update SKY UX

- src/app/components/dropdown/index.html
Pretty sure I added the content to the right section but would also appreciate confirmation :)
> added dismissOnBlur property

- src/app/design/styles/spacing/index.html
update docs to use spacing classes for margin and update horizontal-compact spec to reflect changes to class
> update spacing guidelines

- src/app/components/confirm/index.html
Added `primary` and `list` but not `secondary` because that's what the default value looks like but can edit to be more specific. 
This addresses [Issue #1866](https://github.com/blackbaud/skyux2/issues/1866)
> added options for styleType

- src/app/components/repeater/index.html
added isExpanded property to list. Should the line about accepting boolean values be included or excluded?
This addresses https://github.com/blackbaud/skyux2/issues/1865
> added isExpanded property

- src/app/learn/overview/index.html
Addresses https://github.com/blackbaud/skyux2/issues/2224. ... @Blackbaud-BenLambert, do you think this is addresses the issue sufficiently?
> Add note linking to SKY UX 1

- src/app/components/autocomplete/index.html
Addresses https://github.com/blackbaud/skyux2/issues/2228.
> Update description of autocomplete data property

- src/app/learn/get-started/basics/create-project/index.html
- src/app/learn/reference/cli-commands/build/index.html
- src/app/learn/reference/cli-commands/cli-commands-action-button.component.ts
- src/app/learn/reference/cli-commands/e2e/index.html
- src/app/learn/reference/cli-commands/install/index.html
- src/app/learn/reference/cli-commands/new/index.html
- src/app/learn/reference/cli-commands/serve/index.html
- src/app/learn/reference/cli-commands/test/index.html
- src/stache/includes/cli/name.html
- src/stache/includes/cli/repo.html
Addresses https://github.com/blackbaud/skyux2/issues/2250 and https://github.com/blackbaud/skyux2/issues/2195. And https://github.com/blackbaud/skyux2/issues/2251.
> Update CLI reference docs

- src/app/components/tile/index.html
> Fix showHelp default. Make showSettings match description

- src/app/components/action-button/index.html
> Action button permalink docs

- src/app/learn/reference/cli-commands/test/index.html
- src/app/learn/reference/cli-commands/watch/index.html
- src/stache/includes/cli/coverage.html
Addresses https://github.com/blackbaud/skyux2/issues/2309.
> Document coverage flag

- src/app/components/list/grid/index.html
- src/app/components/list/toolbar/index.html
Addresses https://github.com/blackbaud/skyux2/issues/1706.
> Document help button

- src/app/components/paging/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/281 and https://github.com/blackbaud/skyux2-docs/issues/295.
> Update paging label property and clean up paging docs

- src/app/components/tabs/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/310.
> Add page title guideline to tab docs

- src/app/components/repeater/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/326.
> Remove duplicate entry for isExpanded

- src/app/contribute/guidelines/index.html
- src/app/learn/get-started/prereqs/initial-setup/index.html
- src/app/learn/reference/cli-commands/lint/index.html
- src/app/learn/reference/cli-commands/test/index.html
- src/app/learn/reference/cli-commands/watch/index.html
- src/stache/includes/cli/lint-fix.html
- src/stache/includes/cli/lint-format.html
- src/stache/includes/tslint-tool.html
Doc tweaks to the docs for the new lint flags, and also update docs for recommended tools to address https://github.com/blackbaud/skyux2-docs/issues/322.
> Doc tweaks to lint flags and update recommended tools

- src/app/contribute/guidelines/index.html
- src/app/learn/get-started/prereqs/initial-setup/index.html
- src/app/learn/reference/cli-commands/lint/index.html
- src/app/learn/reference/cli-commands/test/index.html
- src/app/learn/reference/cli-commands/watch/index.html
- src/stache/includes/cli/lint-fix.html
- src/stache/includes/cli/lint-format.html
- src/stache/includes/tslint-tool.html
Also addresses https://github.com/blackbaud/skyux2-docs/issues/322.
> Added fix and format flags

- src/app/components/demo-components.service.ts
- src/app/components/email-validation/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/346.
> Docs clean up for email validation

- src/app/components/colorpicker/index.html
- src/app/components/help-inline/index.html
Addresses issue https://github.com/blackbaud/skyux2-docs/issues/297
> updated intro text to match date and time pickers

- src/app/components/radio/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/356 to document the work in https://github.com/blackbaud/skyux-forms/pull/26.
> Document ariaLabel for radio button group

- src/app/components/action-button/index.html
- src/app/components/code-block/index.html
- src/app/components/copy-to-clipboard/index.html
- src/app/components/definition-list/index.html
- src/app/components/fileattachments/index.html
- src/app/components/fluid-grid/index.html
- src/app/components/help-inline/index.html
- src/app/components/infinite-scroll/index.html
- src/app/components/key-info/index.html
- src/app/components/link-records/index.html
- src/app/components/media-queries/index.html
- src/app/components/page-summary/index.html
- src/app/components/progress-indicator/index.html
- src/app/components/radio/index.html
- src/app/components/sectioned-form/index.html
- src/app/components/select-field/index.html
- src/app/components/status-indicator/index.html
- src/app/components/summary-actionbar/index.html
- src/app/components/text-expand/index.html
- src/app/components/url-validation/index.html
Style cleanup on component docs. Addresses https://github.com/blackbaud/skyux2-docs/issues/365.
> Fix capitalization in main header on component docs

- src/app/learn/accessibility/test/index.html
- src/app/learn/get-started/advanced/accessibility-analyzer/index.html
- src/app/learn/get-started/advanced/accessibility-unit-tests/index.html
- src/app/learn/get-started/advanced/add-entry-components/index.html
- src/app/learn/get-started/advanced/include-static-assets/index.html
- src/app/learn/get-started/advanced/localization/index.html
- src/app/learn/get-started/advanced/module-level-providers/index.html
- src/app/learn/get-started/advanced/route-params/index.html
- src/app/learn/get-started/advanced/route-wildcard/index.html
- src/app/learn/get-started/advanced/unit-test-modals/index.html
- src/stache/includes/e2e-recommendation-accessibility.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/358
Also including Isaac for review to make sure I addressed his suggestion correctly
> Added link for a11y unit tests & updated recommendation

- src/app/components/select-field/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/269.
> Create SkySelectField section

- src/app/learn/accessibility/code/index.html
- src/app/learn/accessibility/design/checklist/index.html
- src/app/learn/accessibility/design/index.html
- src/app/learn/accessibility/test/index.html
- src/app/learn/get-started/basics/create-project/index.html
- src/app/learn/get-started/basics/edit-project/index.html
- src/app/learn/get-started/basics/run-tests/index.html
- src/app/learn/get-started/basics/serve-project/index.html
- src/app/learn/get-started/prereqs/initial-setup/index.html
- src/app/learn/get-started/prereqs/ssl-certificate/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/369. Also fixes capitalization styles in H1 headers for various topics.
> Update Node prereqs

- .travis.yml
- src/app/learn/get-started/basics/update-cli/index.html
- src/app/learn/get-started/prereqs/initial-setup/index.html
- src/app/learn/reference/faq/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/387
> Updated references to @skyux-sdk/cli

- src/app/learn/get-started/advanced/route-params/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/321. And https://github.com/blackbaud/skyux2-docs/issues/385.
> Document route parameter recommendation

- src/app/learn/reference/helpers/SkyAuthHttpClientModule/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/391.
> Fix SkyAuthHttpClientModule typo

- package.json
- skyuxconfig.json
- src/app/components/form/index.html
- src/app/components/shared/demo-page-code.component.html
- src/app/components/shared/demo-page.component.html
- src/app/components/shared/demo-page.component.ts
- src/app/learn/get-started/advanced/accessibility-analyzer/index.html
- src/app/learn/get-started/advanced/accessibility-unit-tests/index.html
- src/app/learn/get-started/advanced/add-entry-components/index.html
- src/app/learn/get-started/advanced/include-static-assets/index.html
- src/app/learn/get-started/advanced/localization/index.html
- src/app/learn/get-started/advanced/module-level-providers/index.html
- src/app/learn/get-started/advanced/pact-tests/index.html
- src/app/learn/get-started/advanced/route-params/index.html
- src/app/learn/get-started/advanced/route-wildcard/index.html
- src/app/learn/get-started/advanced/unit-test-modals/index.html
- src/app/learn/get-started/basics/edit-project/index.html
- src/app/learn/get-started/basics/navigate-spa/index.html
- src/app/learn/reference/component-libraries/index.html
- src/app/learn/reference/configuration/additional-config-files/index.html
- src/app/learn/reference/configuration/apply-appsettings/index.html
- src/app/learn/reference/configuration/index.html
- src/app/learn/reference/helpers/SkyAuthHttpClientModule/index.html
Highjacking @Blackbaud-BrandonJones #395, but including the fix for his small linting issue.
> Feature maintenance

- src/app/components/repeater/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/338
> Added repeater item events

- src/app/learn/get-started/advanced/accessibility-unit-tests/index.html
Replaces https://github.com/blackbaud/skyux2-docs/pull/403 so that checks will pass.
> Update testing library link

- src/app/learn/reference/cli-commands/e2e/index.html
- src/app/learn/reference/cli-commands/test/index.html
- src/app/learn/reference/cli-commands/watch/index.html
- src/stache/includes/cli/headless.html
Fixes https://github.com/blackbaud/skyux2-docs/issues/397
> Added headless flag

- package.json
- src/app/components/demo-components.service.ts
- src/app/components/text-expand-repeater/index.html
- src/app/components/text-expand/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/389 and https://github.com/blackbaud/skyux2-docs/issues/394.
Marking on hold until https://github.com/blackbaud/skyux2/pull/2334 is available to update the demos as well.
> Split out text expand docs

- src/app/components/code-block/index.html
- src/app/components/copy-to-clipboard/index.html
- src/app/components/icon/index.html
- src/app/components/infinite-scroll/index.html
- src/app/components/list/overview/index.html
- src/app/components/shared/demo-page.component.html
- src/app/components/summary-actionbar/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/341. Also cleans up a handful of component topics where the module and/or package were not displaying correctly. (There are several others I wasn't able to fix here. I will create a separate issue for those after this update.)
> Add guidance to Installation section

- src/app/components/label/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/427
> Corrected label package name

- src/app/components/grid/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/420.
> Update sortField property and break out ListSortFieldSelectorModel docs

- src/app/components/numeric/index.html
- src/app/components/paging/index.html
- src/app/components/shared/demo-page.component.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/425, https://github.com/blackbaud/skyux2-docs/issues/426, and https://github.com/blackbaud/skyux2-docs/issues/428.
> Various updates to address feedback

- src/app/design/guidelines/user-assistance/index.html
Let me know if I need to elaborate more.
Addresses https://github.com/blackbaud/skyux2-docs/issues/404
> Added UA guidelines for empty-state help

- src/app/components/progress-indicator/index.html
- src/app/components/wizard/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/440.
> Remove stray parenthesis on displayMode property;

- src/app/learn/get-started/advanced/localization/index.html
Removed extra letter in package name
> Fixed typo

- src/app/learn/get-started/basics/build-publish/index.html
- src/app/learn/get-started/basics/create-project/index.html
- src/app/learn/get-started/basics/navigate-spa/index.html
- src/app/learn/get-started/basics/run-tests/index.html
- src/app/learn/get-started/basics/serve-project/index.html
- src/app/learn/get-started/basics/update-cli/index.html
- src/app/learn/get-started/basics/update-components/index.html
Straightforward procedure but let me know if I should add any additional notes or more to the page summary.
Addresses https://github.com/blackbaud/skyux2-docs/issues/409
> Added build & publish for external developers

- src/app/learn/get-started/advanced/include-static-assets/index.html
Fixes https://github.com/blackbaud/skyux2-docs/issues/268 (in conjunction with https://github.com/blackbaud/skyux2-docs/pull/65)
> Documented SkyAppAssetsService case sensitivity.

- src/app/components/avatar/index.html
- src/app/components/demo-components.service.ts
Addresses https://github.com/blackbaud/skyux2-docs/issues/462.
> Clean up avatar docs

- src/app/learn/get-started/advanced/create-plugin/index.html
- src/app/learn/reference/extensibility/index.html
- src/app/learn/reference/reference-action-button.component.ts
> Document builder plugin

- src/app/learn/get-started/advanced/sticky-settings/index.html
Fixes https://github.com/blackbaud/skyux2-docs/issues/264
> Initial creation of the public sticky settings docs.

- src/app/components/shared/demo-page.component.html
- src/app/components/shared/demo-page.component.scss
- src/app/components/shared/tabbed-demo-page.component.html
- src/app/components/shared/tabbed-demo-page.component.scss
- src/app/learn/index.html
- src/app/shared/home-component/home.component.scss
Cleaning up a couple visual regressions introduced in https://github.com/blackbaud/skyux2-docs/pull/377
> Fixed styles missing on homepage.  Fixed leaky overrides on component pages

- src/app/design/guidelines/index.html
- src/app/design/principles/index.html
- src/app/design/resources/index.html
- src/app/design/styles/color/index.html
- src/app/design/styles/icons/index.html
- src/app/design/styles/index.html
- src/app/design/styles/typography/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/475
> Miscellaneous edits to Design section

- src/app/components/popover/index.html
- src/app/components/shared/tabbed-demo-page.component.scss
- src/app/components/tabs/index.html
- src/app/shared/home-component/home.component.scss
- src/app/styles.scss
check:
Homepage
Components > Flyout
Components > Popover
Components > Tabs
Design > Guidelines > Manage Records
> fix screenshots

- src/app/components/grid/index.html
- src/app/components/list/grid/index.html
- src/app/components/tile/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/514.
> Update settingsKey descriptions and links

- src/app/components/dropdown/index.html
Addresses issue https://github.com/blackbaud/skyux2-docs/issues/528
> Added items to SkyDropdownMenuChange

- src/app/components/flyout/index.html
On hold pending https://blackbaud.visualstudio.com/Products/_git/skyux-spa-ui-config-service-docs/pullrequest/62678?_a=files.
Addresses https://github.com/blackbaud/skyux2-docs/issues/535.
> Add settingsKey docs for flyouts

- src/app/components/filter/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/566.
> Update filter component UX guidelines

- src/app/components/datepicker/index.html
- src/app/components/list/grid/index.html
Added dependency information to address https://github.com/blackbaud/skyux2-docs/issues/294 and https://github.com/blackbaud/skyux2-docs/issues/518
> Added dependency information for list view grid and datepicker

- src/app/components/list/checklist/index.html
Replaces https://github.com/blackbaud/skyux2-docs/pull/585 because the tests in that PR seem to be stuck.
> Fix list checklist typo

- src/stache/includes/supported-browsers.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/597.
> Update Edge and IE browser support docs

- src/app/components/list/overview/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/609.
> Update data property description for list component

- src/app/components/repeater/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/590
> Added activeIndex property

- package-lock.json
- package.json
- src/app/components/phone-field/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/588
Wasn't sure if the note was better suited in the intro or Behavior & States > Country selection section.
> Added note about switching country through dial code

- package-lock.json
- src/app/components/action-button/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/606
I'm not in love with the way I handled the addition; definitely open to feedback.
> Added info about commands property

- package-lock.json
- src/app/learn/get-started/advanced/route-guards/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/619.
> Remove stray closing tag in code sample

- src/app/components/confirm/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/633 to document new property from https://github.com/blackbaud/skyux-modals/pull/65.
> Document preserveWhitespace property

- src/app/components/select-field/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/563
*Chatted with Alex and we can leave `index` out because it's not for the consumer
> Added description property to SkySelectField properties

- src/app/components/grid/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/638.
> Update locked property description for grids

- src/app/components/datepicker/index.html
Suggested changes to the new fuzzy date docs after reviewing https://github.com/blackbaud/skyux2-docs/pull/659, plus some tweaks to the existing docs.
> Tweaks to datepicker docs after review of fuzzy datepicker docs

- src/app/learn/get-started/basics/build-publish/index.html
- src/app/learn/reference/configuration/index.html
Dependent on https://github.com/blackbaud/skyux-config/pull/26 and https://github.com/blackbaud/skyux-sdk-builder/pull/165 first.
> Documented app base property.

- src/app/components/demo-components.service.ts
- src/app/components/file-attachments/file-attachment/index.html
- src/app/components/file-attachments/file-attachments-action-button.component.ts
- src/app/components/file-attachments/index.html
- src/app/components/file-attachments/single-file-attachment/index.html
- src/app/demos/single-file-attachment/single-file-attachment-demo.component.html
Also addresses https://github.com/blackbaud/skyux2-docs/issues/699.
> Edits to new file attachment docs

- package-lock.json
- package.json
Issue: https://github.com/blackbaud/skyux-progress-indicator/issues/25
> Upgrade progress indicator

- src/app/components/list/grid/index.html
- src/app/learn/get-started/advanced/sticky-settings/integrations/skyux-components/grids/index.html
Replaces https://github.com/blackbaud/skyux2-docs/pull/737 and makes additional doc tweaks
> Update sticky settings docs for list view grid

- src/stache/includes/cli/template.html
References https://github.com/blackbaud/skyux2-docs/issues/695
> Added barebones as template option

- src/app/learn/reference/configuration/additional-config-files/index.html
Making the change in https://github.com/blackbaud/skyux2-docs/pull/745 to get checks to pass.
> Fix config file code sample

- src/app/components/repeater/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/746. I assume this is good to go since we released https://github.com/blackbaud/skyux-lists/pull/91.
> Document tag property and related event for repeaters

- package-lock.json
- src/app/learn/get-started/advanced/sticky-settings/integrations/custom-components/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/769.
> Fix sticky settings code sample

- package-lock.json
- src/app/learn/get-started/prereqs/index.html
For code change https://github.com/blackbaud/skyux-sdk-cli/pull/52
> Updated Firefox and iOS Simulator docs.

- package-lock.json
- src/app/components/text-highlight/index.html
Added note about where the text highlight directive can be placed. References https://github.com/blackbaud/skyux2-docs/issues/694
> Added note about text highlight directive

- src/app/learn/reference/cli-commands/cli-commands-action-button.component.ts
- src/app/learn/reference/cli-commands/upgrade/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/484.
> Add docs for skyux upgrade command

- package-lock.json
- src/app/components/fluid-grid/index.html
> Document fluid-grid gutterSize and disableMargin properties

- src/app/components/progress-indicator/passive-progress-indicator/index.html
- src/app/components/progress-indicator/waterfall-progress-indicator/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/463.
> Highlight sequential nature of progress indicators

- src/app/learn/reference/configuration/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/360.
> Document notifySlack and notifySlackUrl properties

- package-lock.json
- src/app/design/styles/icons/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/758
> Updated docs and examples to use icon component

- src/app/learn/reference/cli-commands/build-public-library/index.html
- src/stache/includes/cli/template-check.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/834
> Added fullTemplateTypeCheck to build-public-library

- src/app/demos/demos.service.ts
> Added missing inline form demo files to demo

- src/app/components/split-view/index.html
> Added default width to split-view drawer component

- src/app/learn/reference/cli-commands/new/index.html
- src/stache/includes/cli/checkout.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/856.
> Add checkout flag for skyux new

- src/app/components/select-field/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/865 and https://github.com/blackbaud/skyux2-docs/issues/868.
> Document new select field options

- src/app/components/avatar/index.html
Replaces https://github.com/blackbaud/skyux2-docs/pull/862 so that checks will pass.
Addresses https://github.com/blackbaud/skyux2-docs/issues/871.
> Document new maxFileSize property

- src/app/components/fluid-grid/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/872.
> Add default for screenXSmall property

- src/app/demos/date-range-picker/date-range-picker-demo.component.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/877.
> Update date range picker demo error messages

- src/app/components/tile/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/880.
> Add link from tile docs to empty-state help guidelines

- src/app/components/form/index.html
- src/app/design/guidelines/form-design/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/379.
> Update placeholder text guidelines

- src/app/components/tile/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/883 and https://github.com/blackbaud/skyux2-docs/issues/892.
> Update tile guidelines

- package-lock.json
- src/app/components/demo-components.service.ts
Addresses #740 
We were missing a dependency on `Dragula`.
> Grid and tile component demos now load properly

- src/app/components/demo-components.service.ts
> enable sectioned form demo

- src/app/components/shared/demo-page-stackblitz-service.ts
Issue: https://github.com/blackbaud/skyux2-docs/issues/910
> Fix StackBlitz

- src/app/components/phone-field/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/927. I confirmed the change at https://github.com/blackbaud/skyux-phone-field/blob/master/src/app/public/modules/phone-field/phone-field.component.ts#L123.
> Fix name of phone field event

- src/app/components/grid/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/929.
> Document alignment property for grids`

- src/app/contribute/packages/packages.component.html
Replaces https://github.com/blackbaud/skyux2-docs/pull/944 so that checks will pass.
> Fix Packages matrix link

- src/stache/includes/cli/template.html
> Added template branch requirement.

- src/app/components/flyout/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/956.
> Update defaultWidth property description for flyout

- src/app/learn/get-started/advanced/route-guards/index.html
Improve the imports so the example is closer to compiling out of the gate
> Improve the code sample

- src/app/design/guidelines/buttons-links/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/970.
> Add tooltip guidance

- src/stache/includes/cli/checkout.html
- src/stache/includes/cli/template.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/981.
> Update default for checkout flag

- src/app/components/grid/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/988.
> Update grid width property

- src/app/components/error/index.html
- src/app/design/guidelines/error-handling/index.html
Addresses the property updates called out in https://github.com/blackbaud/skyux2-docs/issues/879.
The https://github.com/blackbaud/skyux2-demos/pull/50 PR addresses the UI text feedback.
> Updated property descriptions

- src/app/contribute/contribution-process/guidelines/index.html
- src/app/contribute/contribution-process/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/967.
> Add testing fixtures to contribution guidelines

- src/app/learn/get-started/advanced/localization/index.html
> Updated locale example to use modern rxjs

- src/app/components/grid/index.html
Addresses comments in https://github.com/blackbaud/skyux2-docs/issues/988. Also updates the parent component's width property description to call out pixels.
> Update grid width properties

- src/app/components/lookup/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/992.
> Add missing ARIA properties

- src/app/learn/accessibility/design/checklist/index.html
- src/app/styles.scss
Addresses https://github.com/blackbaud/skyux2-docs/issues/922
Swapped out checkboxes and edited the table styles to fix an issue where the checkboxes weren't inside the box after it was marked.
> Swapped checkboxes for SKY UX checkboxes

- src/app/components/toast/index.html
References https://github.com/blackbaud/skyux-toast/issues/53
I wanted to bring attention to the note, but let me know if we should use something different than the alert or if I should use a different alert type.
> Added autoClose docs & note

- src/app/learn/get-started/advanced/accessibility-unit-tests/index.html
Related: https://github.com/blackbaud/skyux-sdk-testing/pull/37
> Document `expectAsync().toBeAccessible()`

- src/app/learn/get-started/basics/modules/index.html
- src/app/learn/reference/cli-commands/upgrade/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/1018.
> Upgrade description of skyux upgrade

- package-lock.json
- src/app/learn/reference/configuration/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/1013
> Added link to a11y test from Configuration

- src/app/learn/get-started/basics/edit-project/index.html
Addresses issue https://github.com/blackbaud/skyux2-docs/issues/1011
> Added step for app-sky.modules file

- src/app/learn/get-started/prereqs/index.html
Addresses https://github.com/blackbaud/skyux2-docs/issues/1035. After discussing in standup, we decided this info would work better as a tip about CLI commands than as a full section. @blackbaud-svossen confirmed that he ran into the same thing when he joined the team.
@Blackbaud-TerryHelems, I assigned you as the reviewer because the team agreed that you should sign off on whatever we add to the docs here.
> Add PowerShell tip

- src/app/contribute/contribute-action-button.component.html
Moved Denise to contributors section
> RIP Denise

- src/app/contribute/contribution-process/file-issue/index.html
- src/app/contribute/contribution-process/index.html
Addresses https://dev.azure.com/blackbaud/Products/_workitems/edit/1702623.
> Update verbiage for filing issues

- src/app/learn/reference/component-libraries/index.html
Replace the reference to Travis-CI with GitHub Actions.
> Remove reference to Travis-CI

- .vscode/settings.json
- package-lock.json
- src/app/demos/data-entry-grid/data-entry-grid-demo.component.html
- src/app/demos/data-entry-grid/data-entry-grid-demo.component.ts
update settings. update package-lock.
> add 'no results found' message to data entry grid demo
